/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecebimentosRouteImport } from './routes/recebimentos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamiliasIndexRouteImport } from './routes/familias.index'
import { Route as FamiliasIdRouteImport } from './routes/familias.$id'

const RecebimentosRoute = RecebimentosRouteImport.update({
  id: '/recebimentos',
  path: '/recebimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasIndexRoute = FamiliasIndexRouteImport.update({
  id: '/familias/',
  path: '/familias/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasIdRoute = FamiliasIdRouteImport.update({
  id: '/familias/$id',
  path: '/familias/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/painel': typeof PainelRoute
  '/recebimentos': typeof RecebimentosRoute
  '/familias/$id': typeof FamiliasIdRoute
  '/familias/': typeof FamiliasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/painel': typeof PainelRoute
  '/recebimentos': typeof RecebimentosRoute
  '/familias/$id': typeof FamiliasIdRoute
  '/familias': typeof FamiliasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/painel': typeof PainelRoute
  '/recebimentos': typeof RecebimentosRoute
  '/familias/$id': typeof FamiliasIdRoute
  '/familias/': typeof FamiliasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimento'
    | '/auth'
    | '/configuracoes'
    | '/estoque'
    | '/painel'
    | '/recebimentos'
    | '/familias/$id'
    | '/familias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendimento'
    | '/auth'
    | '/configuracoes'
    | '/estoque'
    | '/painel'
    | '/recebimentos'
    | '/familias/$id'
    | '/familias'
  id:
    | '__root__'
    | '/'
    | '/atendimento'
    | '/auth'
    | '/configuracoes'
    | '/estoque'
    | '/painel'
    | '/recebimentos'
    | '/familias/$id'
    | '/familias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRoute
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EstoqueRoute: typeof EstoqueRoute
  PainelRoute: typeof PainelRoute
  RecebimentosRoute: typeof RecebimentosRoute
  FamiliasIdRoute: typeof FamiliasIdRoute
  FamiliasIndexRoute: typeof FamiliasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recebimentos': {
      id: '/recebimentos'
      path: '/recebimentos'
      fullPath: '/recebimentos'
      preLoaderRoute: typeof RecebimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias/': {
      id: '/familias/'
      path: '/familias'
      fullPath: '/familias/'
      preLoaderRoute: typeof FamiliasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias/$id': {
      id: '/familias/$id'
      path: '/familias/$id'
      fullPath: '/familias/$id'
      preLoaderRoute: typeof FamiliasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRoute,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EstoqueRoute: EstoqueRoute,
  PainelRoute: PainelRoute,
  RecebimentosRoute: RecebimentosRoute,
  FamiliasIdRoute: FamiliasIdRoute,
  FamiliasIndexRoute: FamiliasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
